services:
  - type: web
    name: bot-binance1.0
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BINANCE_API_KEY
        value: ${BINANCE_API_KEY}
      - key: BINANCE_API_SECRET
        value: ${BINANCE_API_SECRET}
      - key: WEBHOOK_SECRET
        value: ${WEBHOOK_SECRET}
